### PR TITLE
Initial changes for realtime online status

### PR DESCRIPTION
**Pull request by ychino**
Newman, I think this fixes realtime status update issue but when I came from chatroom back to the main page, all avatars won't be listed. Is that why you have `cache` stuff in your code?

### CODE REVIEW

**Comment by IniZio** [comment]
Yes, i put it outside the component so that it is persisted even if all ProfileCache components are unmounted

**Comment by ychino** [comment]
Thank you for your advise as always :)  I don't get why avatars are not rendered when I came from chatroom back to the main page even thought the `componentDidMount` in ProfileCache is called again when `GetProfile` is called in ListCard upon Main.js is mounted anyway, right?

**Comment by IniZio** [comment]
I can't see any special change in this pr that will solve the online status issue though? :thinking:

**Comment by IniZio** [comment]
O wait i understand why now :joy: . Apparently https://github.com/awesomechat/craigschat/blob/dev/src/hocs/ProfileCache.js#L22 will make it not subscribe to value change event if there is cache.

**Comment by ychino** [comment]
I just wanted to tackle with this issue with minimum code to figure out what the route cause this. Thank you. Hmm, when I remove that return from your code, it works mostly but sometimes it doesn't catch the change listener in same cases. 

Does it work perfectly on your machine? If we keep having this ambiguity, we might want to try alternative solution for this. Do you think of any other solution from your experience even if it's against DRY?

**Pull request closed without merging**
