### PR TITLE
Firebase redo

### PR DESCRIPTION
**Pull request by ychino**
If you have time.....

Main Changes are for storing chatrooms to Firestore to query them.

### CODE REVIEW

**Comment by IniZio** [comment]
Seems it does not redirect on create room? the rest works fine :+1:

**Comment by ychino** [comment]
Thanks! Oh, doesn't it redirect to Home on creating a room???

**Comment by IniZio** [comment]
No :thinking:

**Comment by ychino** [comment]
Hmm, it seems it works on my end. Please let me deploy it to see how it works.

**Pull request merged**
